### ISSUE TITLE
How to try out? Missing static folder

### ISSUE THREAD

**Issue by grzs** [paradoxxxzero/kalong#19]
Hi Mounier,

Is it possible to play around with your new debugger? I wanted to try out, but the kalong/static dir is empty.
Thanks,
Janos

**Comment by paradoxxxzero** [comment]
Hello!

If you install it from [pypi](https://pypi.org/project/kalong/) you should have the static files, but if you just cloned the git you have to build them:

```
$ yarn install
$ yarn build
```

Have fun with it :)

**Comment by grzs** [comment]
Great, thanks!
